### ISSUE TITLE
Client error: AMQJS0011E Invalid state not connected

### ISSUE THREAD

**Issue by topdayday** [nanomq/nanomq#1033]
We use Paho.MQTT.Client Js SDK.
The browser client occasionally displays the following exceptions:

chunk-libs.d564d476.js:46 Error: AMQJS0011E Invalid state not connected.
    at S.send (chunk-libs.d564d476.js:54:33989)
    at x.send (chunk-libs.d564d476.js:54:52364)
    at a.mqtt_send (chunk-551c1f8b.9d4808e5.js:12:281308)

And  NanoMQ  server log  displays the following exceptions:

2023-02-04 16:27:40 [13942] WARN  /home/runner/work/nanomq/nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:581: nni aio recv error!! 31
2023-02-04 16:27:40 [13942] WARN  /home/runner/work/nanomq/nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:817: tcptran_pipe_recv_cb: recv error rv: 137

How can I solve it?

**Comment by JaylinYu** [comment]
Thanks you for using nanomq, nng aio error 31 means NNG_ECONNSHUT, It indicates the TCP socket has been closed by the kernel due to some issue (more likely network unstable)

I suggest you set keepalive to 5-20 sec and implement an auto-reconnect capability in your client, since diagnostic networking issue is not an easy thing, especially from the browser side.
