### ISSUE TITLE
Heap-Buffer-Overflow in get_var_integer Function of NanoMQ at mqtt_parser.c:174

### ISSUE THREAD

**Issue by dqp10515** [nanomq/nanomq#1720]
**Describe the bug**
A heap-buffer-overflow error was detected by AddressSanitizer in the `get_var_integer` function of `nanomq`. The function attempts to read beyond the allocated heap buffer, leading to undefined behavior. The issue occurs specifically at line 174 in `mqtt_parser.c`, where the function tries to access a byte that is just beyond the allocated memory block. This indicates that the bounds of the buffer are not being correctly respected, potentially due to incorrect assumptions about the size of the buffer or an error in the calculation of the index.

**Expected behavior**
`get_var_integer` should safely parse the variable integer within the bounds of the provided buffer. No overflow of the buffer should occur during normal operation.

**Actual Behavior**
The function `get_var_integer` caused a heap-buffer-overflow by reading past the end of a 14-byte allocated buffer. The buffer was expected to contain a variable-length integer, but the function continued to read past the buffer's end, resulting in undefined behavior and a runtime error. AddressSanitizer reported that the read operation occurred at an address that was beyond the allocated range, specifically 0 bytes to the right of a 14-byte region.

**To Reproduce**

Follow these steps to reproduce the issue:

1. Compile NanoMQ with ASan and UBSan enabled:

    ```bash
    mkdir nanomq/build
    cd build
    cmake -DBUILD_BENCH=ON -DASAN=ON -DTSAN=ON \
        -DCMAKE_C_COMPILER=clang \
        -DCMAKE_CXX_COMPILER=clang++ \
        -DCMAKE_C_FLAGS="-g -fsanitize=address,undefined -fno-omit-frame-pointer" \
        -DCMAKE_CXX_FLAGS="-g -fsanitize=address,undefined -fno-omit-frame-pointer" \
        -DCMAKE_LD_FLAGS="-fsanitize=address,undefined" \
        ..
    make clean
    make -j 8
    ```

2. Start the NanoMQ server with the following command:

    ```bash
   nanomq/build/nanomq/nanomq start --url nmq-tcp://0.0.0.0:5883 --url nmq-ws://localhost:5885 --max_tq_thread 8 -n 16
    ```

3. Send a series of hexstreams to the server in sequence, which are stored in the file `hexstream.txt` ：
[hexstream.txt](https://github.com/nanomq/nanomq/files/14752229/hexstream.txt)

**Environment Details**
 - NanoMQ version 0.21.7
 - Operating system and version Ubuntu 20.04 LTS
 - Compiler and language used  clang version 12.0.0
 - testing scenario

**Crash Report**
log of server:
```
2024-03-24 23:38:32 [1788480] ERROR nanomq/nng/src/supplemental/nanolib/conf_ver2.c:1534 conf_parse_ver2: Configure file [(null)] or [/etc/nanomq.conf] not found or unreadable
NanoMQ Broker is started successfully!
2024-03-24 23:38:32 [1788493] ERROR nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:335 tcptran_pipe_nego_cb: Illegal CONNECT Packet type 30
2024-03-24 23:38:32 [1788493] ERROR nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:456 tcptran_pipe_nego_cb: connect nego error rv: Protocol error(13)
2024-03-24 23:38:32 [1788498] ERROR nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:335 tcptran_pipe_nego_cb: Illegal CONNECT Packet type 80
2024-03-24 23:38:32 [1788498] ERROR nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:456 tcptran_pipe_nego_cb: connect nego error rv: Protocol error(13)
2024-03-24 23:38:32 [1788490] ERROR nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:456 tcptran_pipe_nego_cb: connect nego error rv: Unknown error #130(130)
2024-03-24 23:38:32 [1788489] WARN  nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:639 tcptran_pipe_recv_cb: nni aio recv error!! Connection shutdown

2024-03-24 23:38:32 [1788489] WARN  nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:907 tcptran_pipe_recv_cb: tcptran_pipe_recv_cb: parse error rv: 139

2024-03-24 23:38:32 [1788488] ERROR nanomq/nng/src/sp/protocol/mqtt/nmq_mqtt.c:1075 nano_pipe_recv_cb: Invalid subscribe packet!
2024-03-24 23:38:32 [1788494] ERROR nanomq/nng/src/sp/protocol/mqtt/nmq_mqtt.c:1075 nano_pipe_recv_cb: Invalid subscribe packet!
2024-03-24 23:38:33 [1788491] ERROR nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:335 tcptran_pipe_nego_cb: Illegal CONNECT Packet type 15
2024-03-24 23:38:33 [1788491] ERROR nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:456 tcptran_pipe_nego_cb: connect nego error rv: Protocol error(13)
2024-03-24 23:38:33 [1788502] ERROR nanomq/nanomq/apps/broker.c:104 sig_handler: signal signumber: 6 received!
```
Here is the ASan report:
```
=================================================================
==1788480==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000b01e at pc 0x000000656aa4 bp 0x7f304dee37a0 sp 0x7f304dee3798
READ of size 1 at 0x60200000b01e thread T20 (nng:task)
    #0 0x656aa3 in get_var_integer nanomq/nng/src/sp/protocol/mqtt/mqtt_parser.c:174:12
    #1 0x65f604 in conn_handler nanomq/nng/src/sp/protocol/mqtt/mqtt_parser.c:593:33
    #2 0x931cb8 in tcptran_pipe_nego_cbnanomq/nng/src/sp/transport/mqtt/broker_tcp.c:374:13
    #3 0x6253ae in nni_taskq_thread nanomq/nng/src/core/taskq.c:50:4
    #4 0x628eb8 in nni_thr_wrap nanomq/nng/src/core/thread.c:94:3
    #5 0x63bb0b in nni_plat_thr_main nanomq/nng/src/platform/posix/posix_thread.c:266:2
    #6 0x7f306706d608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
    #7 0x7f3066dfb292 in clone /build/glibc-eX1tMB/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

0x60200000b01e is located 0 bytes to the right of 14-byte region [0x60200000b010,0x60200000b01e)
allocated by thread T20 (nng:task) here:
    #0 0x4b19ca in malloc /home/brian/src/llvm_releases/llvm-project/llvm/utils/release/final/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3

Thread T20 (nng:task) created by T0 here:
    #0 0x49bd4c in pthread_create /home/brian/src/llvm_releases/llvm-project/llvm/utils/release/final/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:205:3
    #1 0x63b82c in nni_plat_thr_init nanomq/nng/src/platform/posix/posix_thread.c:279:7
    #2 0x6287bb in nni_thr_init nanomq/nng/src/core/thread.c:121:12
    #3 0x624bc6 in nni_taskq_init nanomq/nng/src/core/taskq.c:95:8
    #4 0x627ee4 in nni_taskq_sys_init nanomq/nng/src/core/taskq.c:287:10
    #5 0x5e5cfc in nni_init_helper nanomq/nng/src/core/init.c:35:13
    #6 0x63c3ea in nni_plat_init nanomq/nng/src/platform/posix/posix_thread.c:422:12
    #7 0x5e5ce2 in nni_init nanomq/nng/src/core/init.c:57:10
    #8 0x695e8f in nni_proto_mqtt_open nanomq/nng/src/sp/protocol.c:36:12
    #9 0x6783e7 in nng_nmq_tcp0_open nanomq/nng/src/sp/protocol/mqtt/nmq_mqtt.c:1403:10
    #10 0x59b9f3 in broker nanomq/nanomq/apps/broker.c:937:25
    #11 0x5a9407 in broker_start nanomq/nanomq/apps/broker.c:1742:7
    #12 0x585ad6 in main nanomq/nanomq/nanomq.c:142:10
    #13 0x7f3066d000b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: heap-buffer-overflow nanomq/nng/src/sp/protocol/mqtt/mqtt_parser.c:174:12 in get_var_integer
Shadow bytes around the buggy address:
  0x0c047fff95b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff95c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff95d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff95e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff95f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c047fff9600: fa fa 00[06]fa fa 05 fa fa fa fa fa fa fa fa fa
  0x0c047fff9610: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9620: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9630: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9640: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9650: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==1788480==ABORTING

```

**Comment by OdyWayne** [comment]
issue confirmed, patch is on the way.

**Comment by OdyWayne** [comment]
fixed here --> https://github.com/nanomq/NanoNNG/pull/906
