### ISSUE TITLE
Heap-Buffer-Overflow in read_byte Function of NanoMQ at mqtt_codec.c:2871

### ISSUE THREAD

**Issue by dqp10515** [nanomq/nanomq#1722]
**Describe the bug**
A heap-buffer-overflow error was detected by AddressSanitizer in the `nanomq` MQTT codec module. Specifically, the `read_byte` function attempted to access memory address, which lies just beyond the bounds of an allocated 387-byte buffer. 

**Expected behavior**
The `read_byte` function is expected to check the bounds of the buffer before attempting to read data to ensure that it does not read beyond the allocated memory space. 
**Actual Behavior**
At line 2871 in the `mqtt_codec.c` file, the `read_byte` function attempted to increment its `curpos` pointer and read the value at that position, resulting in an out-of-bounds read. 

**To Reproduce**
Follow these steps to reproduce the issue:

1. Compile NanoMQ with ASan and UBSan enabled:

    ```bash
    mkdir nanomq/build
    cd build
    cmake -DBUILD_BENCH=ON -DASAN=ON -DTSAN=ON \
        -DCMAKE_C_COMPILER=clang \
        -DCMAKE_CXX_COMPILER=clang++ \
        -DCMAKE_C_FLAGS="-g -fsanitize=address,undefined -fno-omit-frame-pointer" \
        -DCMAKE_CXX_FLAGS="-g -fsanitize=address,undefined -fno-omit-frame-pointer" \
        -DCMAKE_LD_FLAGS="-fsanitize=address,undefined" \
        ..
    make clean
    make -j 8
    ```

2. Start the NanoMQ server with the following command:

    ```bash
   nanomq/build/nanomq/nanomq start --url nmq-tcp://0.0.0.0:5883 --url nmq-ws://localhost:5885 --max_tq_thread 8 -n 16
    ```

3. Send a series of hexstreams to the server in sequence, which are stored in the file `hexstream.txt` using the code：
```python
import socket

def send_packet(input):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        s.connect(('127.0.0.1', 5883))
        s.send(input)
    except ConnectionResetError:
        print("Connection was reset.")
    except ConnectionRefusedError:
        print("Connection refused.")
    finally:
        s.close()

with open('hexstream.txt', 'r') as f:
    crash_log = f.read().splitlines()

for c in crash_log:
    clean_c = ''.join(c.split())
    packet = bytearray.fromhex(clean_c)
    send_packet(packet)
```
[hexstream.txt](https://github.com/nanomq/nanomq/files/14754539/hexstream.txt)

**Environment Details**
 - NanoMQ version 0.21.7
 - Operating system and version Ubuntu 20.04 LTS
 - Compiler and language used  clang version 12.0.0
 - testing scenario

**Crash Report**
log of server:
```
2024-03-24 23:53:21 [1895146] ERROR nanomq/nng/src/supplemental/nanolib/conf_ver2.c:1534 conf_parse_ver2: Configure file [(null)] or [/etc/nanomq.conf] not found or unreadable
NanoMQ Broker is started successfully!
2024-03-24 23:53:21 [1895157] ERROR nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:456 tcptran_pipe_nego_cb: connect nego error rv: Protocol error(13)
2024-03-24 23:53:21 [1895156] ERROR nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:456 tcptran_pipe_nego_cb: connect nego error rv: Unknown error #130(130)
2024-03-24 23:53:21 [1895155] ERROR nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:335 tcptran_pipe_nego_cb: Illegal CONNECT Packet type 34
2024-03-24 23:53:21 [1895155] ERROR nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:456 tcptran_pipe_nego_cb: connect nego error rv: Protocol error(13)
2024-03-24 23:53:21 [1895169] ERROR nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:456 tcptran_pipe_nego_cb: connect nego error rv: Unknown error #130(130)
2024-03-24 23:53:21 [1895160] WARN  nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:639 tcptran_pipe_recv_cb: nni aio recv error!! Connection shutdown

2024-03-24 23:53:21 [1895160] WARN  nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:907 tcptran_pipe_recv_cb: tcptran_pipe_recv_cb: parse error rv: 139

2024-03-24 23:53:21 [1895160] WARN  nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:791 tcptran_pipe_recv_cb: 0 Packet ID in QoS Message!
2024-03-24 23:53:21 [1895160] WARN  nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:907 tcptran_pipe_recv_cb: tcptran_pipe_recv_cb: parse error rv: 130

2024-03-24 23:53:21 [1895167] ERROR nanomq/nanomq/pub_handler.c:1139 handle_pub: Topic is NULL
2024-03-24 23:53:21 [1895159] WARN nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:639 tcptran_pipe_recv_cb: nni aio recv error!! Object closed

2024-03-24 23:53:21 [1895159] WARN  nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:907 tcptran_pipe_recv_cb: tcptran_pipe_recv_cb: parse error rv: 139

2024-03-24 23:53:21 [1895168] ERROR nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:456 tcptran_pipe_nego_cb: connect nego error rv: Unknown error #130(130)
2024-03-24 23:53:21 [1895162] ERROR nanomq/nanomq/apps/broker.c:104 sig_handler: signal signumber: 6 received!


```
Here is the ASan report:
```
=================================================================
==1895146==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6140000001c3 at pc 0x0000006e70e5 bp 0x7fdadb493a90 sp 0x7fdadb493a88
READ of size 1 at 0x6140000001c3 thread T14 (nng:task)
    #0 0x6e70e4 in read_byte nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:2871:9
    #1 0x6fd130 in decode_buf_properties nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:3929:12
    #2 0x6fd568 in decode_properties nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:3952:9
    #3 0x4fee61 in decode_pub_message nanomq/nanomq/pub_handler.c:1607:8
    #4 0x4fa0f4 in handle_pub nanomq/nanomq/pub_handler.c:1093:11
    #5 0x58bd55 in server_cb nanomq/nanomq/apps/broker.c:455:17
    #6 0x626485 in nni_task_exec nanomq/nng/src/core/taskq.c:144:3
    #7 0x5d08c3 in nni_aio_finish_impl nanomq/nng/src/core/aio.c:469:3
    #8 0x5d094c in nni_aio_finish_sync nanomq/nng/src/core/aio.c:484:2
    #9 0x68d84b in nano_pipe_recv_cb nanomq/nng/src/sp/protocol/mqtt/nmq_mqtt.c:1217:2
    #10 0x626485 in nni_task_exec nanomq/nng/src/core/taskq.c:144:3
    #11 0x5d08c3 in nni_aio_finish_impl nanomq/nng/src/core/aio.c:469:3
    #12 0x5d094c in nni_aio_finish_sync nanomq/nng/src/core/aio.c:484:2
    #13 0x92f2a7 in tcptran_pipe_recv_cb nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:891:2
    #14 0x6253ae in nni_taskq_thread nanomq/nng/src/core/taskq.c:50:4
    #15 0x628eb8 in nni_thr_wrap nanomq/nng/src/core/thread.c:94:3
    #16 0x63bb0b in nni_plat_thr_main nanomq/nng/src/platform/posix/posix_thread.c:266:2
    #17 0x7fdaec849608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
    #18 0x7fdaec5d7292 in clone /build/glibc-eX1tMB/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

0x6140000001c3 is located 0 bytes to the right of 387-byte region [0x614000000040,0x6140000001c3)
allocated by thread T14 (nng:task) here:
    #0 0x4b1b3f in calloc /home/brian/src/llvm_releases/llvm-project/llvm/utils/release/final/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3

Thread T14 (nng:task) created by T0 here:
    #0 0x49bd4c in pthread_create /home/brian/src/llvm_releases/llvm-project/llvm/utils/release/final/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:205:3
    #1 0x63b82c in nni_plat_thr_init nanomq/nng/src/platform/posix/posix_thread.c:279:7
    #2 0x6287bb in nni_thr_init nanomq/nng/src/core/thread.c:121:12
    #3 0x624bc6 in nni_taskq_init nanomq/nng/src/core/taskq.c:95:8
    #4 0x627ee4 in nni_taskq_sys_init nanomq/nng/src/core/taskq.c:287:10
    #5 0x5e5cfc in nni_init_helper nanomq/nng/src/core/init.c:35:13
    #6 0x63c3ea in nni_plat_init nanomq/nng/src/platform/posix/posix_thread.c:422:12
    #7 0x5e5ce2 in nni_init nanomq/nng/src/core/init.c:57:10
    #8 0x695e8f in nni_proto_mqtt_open nanomq/nng/src/sp/protocol.c:36:12
    #9 0x6783e7 in nng_nmq_tcp0_open nanomq/nng/src/sp/protocol/mqtt/nmq_mqtt.c:1403:10
    #10 0x59b9f3 in broker nanomq/nanomq/apps/broker.c:937:25
    #11 0x5a9407 in broker_start nanomq/nanomq/apps/broker.c:1742:7
    #12 0x585ad6 in main nanomq/nanomq/nanomq.c:142:10
    #13 0x7fdaec4dc0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: heap-buffer-overflow nanomq/nng/src/supplemental/mqtt/mqtt_codec.c:2871:9 in read_byte
Shadow bytes around the buggy address:
  0x0c287fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c287fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c287fff8000: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c287fff8010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c287fff8020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c287fff8030: 00 00 00 00 00 00 00 00[03]fa fa fa fa fa fa fa
  0x0c287fff8040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c287fff8050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c287fff8060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c287fff8070: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c287fff8080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==1895146==ABORTING


```

**Comment by OdyWayne** [comment]
I believe it's also fix via https://github.com/nanomq/nanomq/pull/1721 or https://github.com/nanomq/NanoNNG/pull/903. It will not cause crash in the latest branch.
