### ISSUE TITLE
Bridge forwards will not take effect until retain is set in old_conf.

### ISSUE THREAD

**Issue by wanghaEMQ** [nanomq/nanomq#1799]
**Describe the bug**

When retain in forwards is not set.
```
bridge.mqtt.emqx.forwards.1.remote_topic=fwd/topic1
bridge.mqtt.emqx.forwards.1.local_topic=topic1
```

No forwards information are printed when NanoMQ started.

```
2024-05-28 23:50:50 [196650] INFO  /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:3281  print_bridge_conf: bridge.mqtt.emqx.qcongestion_control:        1
2024-05-28 23:50:50 [196650] INFO  /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:3283  print_bridge_conf: bridge.mqtt.emqx.quic_0rtt:                  true
2024-05-28 23:50:50 [196650] INFO  /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:3287  print_bridge_conf: bridge.mqtt.emqx.tls.enable:                 false
2024-05-28 23:50:50 [196650] INFO  /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:3295  print_bridge_conf: bridge.mqtt.emqx.forwards:
2024-05-28 23:50:50 [196650] INFO  /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:3307  print_bridge_conf: bridge.mqtt.emqx.subscription:
2024-05-28 23:50:50 [196650] INFO  /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:3310  print_bridge_conf: 	[1] remote topic:        jaylin/1
2024-05-28 23:50:50 [196650] INFO  /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:3313  print_bridge_conf: 	[1] local topic:        jaylin/2
2024-05-28 23:50:50 [196650] INFO  /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:3316  print_bridge_conf: 	[1] qos:          1
2024-05-28 23:50:50 [196650] INFO  /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:3318  print_bridge_conf: 	[1] rap:          1
2024-05-28 23:50:50 [196650] INFO  /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:3320  print_bridge_conf: 	[1] rh:           1
```

Meanwhile some leaks found.
```
=================================================================
==196888==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 11 byte(s) in 1 object(s) allocated from:
    #0 0x7fc8c10d8cc7 in calloc (/lib64/libasan.so.8+0xd8cc7) (BuildId: 542ad02088f38edfdba9d4bfa465b2299f512d3e)
    #1 0x7d5221 in strtrim_head_tail /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:108
    #2 0x7d60bd in get_conf_value /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:275
    #3 0x7e3741 in conf_bridge_node_parse_forwards /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:2622
    #4 0x7e7582 in conf_bridge_node_parse_with_name /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:3016
    #5 0x7e7ab2 in conf_bridge_content_parse /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:3057
    #6 0x7e8072 in conf_bridge_parse /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:3072
    #7 0x7d97e6 in conf_parse /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:635
    #8 0x737c94 in broker_start /home/wangha/Documents/nanomq/nanomq/apps/broker.c:1775
    #9 0x72cac0 in main /home/wangha/Documents/nanomq/nanomq/nanomq.c:142
    #10 0x7fc8bfe49b89 in __libc_start_call_main (/lib64/libc.so.6+0x27b89) (BuildId: f888be5f5e7d58e04cabb8c675c7ab94e77dd68c)
    #11 0x7fc8bfe49c4a in __libc_start_main_alias_2 (/lib64/libc.so.6+0x27c4a) (BuildId: f888be5f5e7d58e04cabb8c675c7ab94e77dd68c)
    #12 0x6e8e84 in _start (/home/wangha/Documents/nanomq/build/nanomq/nanomq+0x6e8e84) (BuildId: f53c8027906b2f56e12856101314e9ed69ceebea)

Direct leak of 7 byte(s) in 1 object(s) allocated from:
    #0 0x7fc8c10d8cc7 in calloc (/lib64/libasan.so.8+0xd8cc7) (BuildId: 542ad02088f38edfdba9d4bfa465b2299f512d3e)
    #1 0x7d5221 in strtrim_head_tail /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:108
    #2 0x7d60bd in get_conf_value /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:275
    #3 0x7e3822 in conf_bridge_node_parse_forwards /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:2632
    #4 0x7e7582 in conf_bridge_node_parse_with_name /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:3016
    #5 0x7e7ab2 in conf_bridge_content_parse /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:3057
    #6 0x7e8072 in conf_bridge_parse /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:3072
    #7 0x7d97e6 in conf_parse /home/wangha/Documents/nanomq/nng/src/supplemental/nanolib/conf.c:635
    #8 0x737c94 in broker_start /home/wangha/Documents/nanomq/nanomq/apps/broker.c:1775
    #9 0x72cac0 in main /home/wangha/Documents/nanomq/nanomq/nanomq.c:142
    #10 0x7fc8bfe49b89 in __libc_start_call_main (/lib64/libc.so.6+0x27b89) (BuildId: f888be5f5e7d58e04cabb8c675c7ab94e77dd68c)
    #11 0x7fc8bfe49c4a in __libc_start_main_alias_2 (/lib64/libc.so.6+0x27c4a) (BuildId: f888be5f5e7d58e04cabb8c675c7ab94e77dd68c)
    #12 0x6e8e84 in _start (/home/wangha/Documents/nanomq/build/nanomq/nanomq+0x6e8e84) (BuildId: f53c8027906b2f56e12856101314e9ed69ceebea)

SUMMARY: AddressSanitizer: 18 byte(s) leaked in 2 allocation(s).
```

**Comment by JaylinYu** [comment]
yes, retain flag is a compulsory in old config file, like qos flag in subscription.
As for memleak, totally due to same reason, nanomq discard the invalid bridging config object and ASAN is not happy about it
