### ISSUE TITLE
Run failed on 32bit raspberry pi os latest version whith exception /sysdeps/arm/armv6/strlen.S: No such file or directory.

### ISSUE THREAD

**Issue by FirYuen** [nanomq/nanomq#200]
I build this project on rpi4 with 32bit raspbian,but when i ran nanomq and connect whith mqttx.
Process dead immediately. 
Here is msgs
```
pi@raspberrypi:~/nanomq/build $ nanomq broker start
"nanomq.conf ./etc/nanomq.conf" file not found or unreadable
INFO: invalid input url, using default url: tcp://0.0.0.0:1883
Set the url by editing nanomq.conf or command-line (-url <url>).
Segmentation fault
```
Gdb run
```
pi@raspberrypi:~/nanomq/build $ gdb nanomq
GNU gdb (Raspbian 8.2.1-2) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from nanomq...(no debugging symbols found)...done.
(gdb) set args broker start
(gdb) run
Starting program: /usr/local/bin/nanomq broker start
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
"nanomq.conf ./etc/nanomq.conf" file not found or unreadable
INFO: invalid input url, using default url: tcp://0.0.0.0:1883
Set the url by editing nanomq.conf or command-line (-url <url>).
[New Thread 0xb6bf4450 (LWP 5801)]
[New Thread 0xb63f3450 (LWP 5802)]
[New Thread 0xb5bf2450 (LWP 5803)]
[New Thread 0xb53f1450 (LWP 5804)]
[New Thread 0xb4bf0450 (LWP 5805)]
[New Thread 0xb43ef450 (LWP 5806)]
[New Thread 0xb3bee450 (LWP 5807)]
[New Thread 0xb33ed450 (LWP 5808)]
[New Thread 0xb2bec450 (LWP 5809)]
[New Thread 0xb23eb450 (LWP 5810)]
[New Thread 0xb1bea450 (LWP 5811)]
[New Thread 0xb13e9450 (LWP 5812)]
[New Thread 0xb0be8450 (LWP 5813)]
[New Thread 0xb03e7450 (LWP 5814)]
[New Thread 0xafbe6450 (LWP 5815)]
[New Thread 0xaf3e5450 (LWP 5816)]
[New Thread 0xaebe4450 (LWP 5817)]
[New Thread 0xae3e3450 (LWP 5818)]
[New Thread 0xadbe2450 (LWP 5819)]
[New Thread 0xad3e1450 (LWP 5820)]
[New Thread 0xacbe0450 (LWP 5821)]

Thread 9 "nng:task" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb33ed450 (LWP 5808)]
strlen () at ../sysdeps/arm/armv6/strlen.S:26
26	../sysdeps/arm/armv6/strlen.S: No such file or directory.
(gdb) bt
#0  strlen () at ../sysdeps/arm/armv6/strlen.S:26
#1  0xb6c39de0 in _IO_vfprintf_internal (s=s@entry=0xb33ec940, 
    format=format@entry=0x7bbb4 "{\"username\":\"%s\", \"ts\":%lu,\"proto_name\":\"%s\",\"keepalive\":%d,\"return_code\":\"%x\",\"proto_ver\":%d,\"client_id\":\"%s\", \"clean_start\":%d}", ap=..., ap@entry=...) at vfprintf.c:1638
#2  0xb6c5d278 in _IO_vsnprintf (string=0xb33eca9c "{\"username\":\"(null)\", \"ts\":1039882450,\"proto_name\":\"", 
    maxlen=<optimized out>, 
    format=0x7bbb4 "{\"username\":\"%s\", \"ts\":%lu,\"proto_name\":\"%s\",\"keepalive\":%d,\"return_code\":\"%x\",\"proto_ver\":%d,\"client_id\":\"%s\", \"clean_start\":%d}", format@entry=0xb33ecbc4 "\314\021\003", args=..., args@entry=...)
    at vsnprintf.c:114
#3  0xb6c3f4d8 in __GI___snprintf (s=<optimized out>, maxlen=<optimized out>, 
    format=0x7bbb4 "{\"username\":\"%s\", \"ts\":%lu,\"proto_name\":\"%s\",\"keepalive\":%d,\"return_code\":\"%x\",\"proto_ver\":%d,\"client_id\":\"%s\", \"clean_start\":%d}") at snprintf.c:33
#4  0x00050dc8 in nano_msg_notify_connect ()
#5  0x000311cc in server_cb ()
#6  0x00046c84 in nni_task_exec ()
#7  0x00038564 in nni_aio_finish_impl ()
#8  0x000385f8 in nni_aio_finish_sync ()
#9  0x00037978 in nng_aio_finish_sync ()
#10 0x00030670 in server_cb ()
#11 0x00046c84 in nni_task_exec ()
#12 0x00038564 in nni_aio_finish_impl ()
#13 0x000385f8 in nni_aio_finish_sync ()
#14 0x0004eb70 in nano_pipe_recv_cb ()
#15 0x00046834 in nni_taskq_thread ()
#16 0x00047428 in nni_thr_wrap ()
#17 0x0004b424 in nni_plat_thr_main ()
#18 0xb6f95494 in start_thread (arg=0xb33ed450) at pthread_create.c:486
#19 0xb6cce578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 
```
Raspberry Pi OS Lite
Release date: May 7th 2021
Kernel version: 5.10
```
pi@raspberrypi:~/nanomq/build $ uname -a
Linux raspberrypi 5.10.52-v7l+ #1441 SMP Tue Aug 3 18:11:56 BST 2021 armv7l GNU/Linux
pi@raspberrypi:~/nanomq/build $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

```

**Comment by JaylinYu** [comment]
Thanks for reporting, gonna fix this soon.
