### ISSUE TITLE
Null Pointer Dereference

### ISSUE THREAD

**Issue by keymandll** [nanomq/nanomq#205]
# NanoMQ 0.4.5 Null Pointer Dereference

## Affected

NanoMQ 0.4.5

DJBHashn @ nng/src/sp/protocol/mqtt/mqtt_parser.c:675 as called from tcptran_pipe_send_start @ nng/src/sp/transport/tcp/tcp.c:743

## How to Reproduce

Send the below CONNECT message to NanoMQ:

```
"\x10\x28\x00\x02\x4d\x51\x54\x54\x04\xc2\x00\x3c\x00\x0b\x74\x65" \
"\x73\x74\x2d\x70\x79\x74\x68\x6f\x6e\x00\x05\x61\x64\x6d\x69\x6e" \
"\x00\x08\x70\x61\x73\x73\x77\x6f\x72\x64"
```

The field triggering the issue in the above message is `mqtt.proto_len` with value `\x00\x02` (bytes #3-4).

### Backtrace

```
(gdb) bt
#0  0x0000562bf89621c2 in DJBHashn ()
#1  0x0000562bf895f3ac in nano_session_restore ()
#2  0x0000562bf895fdda in nano_pipe_start ()
#3  0x0000562bf895749f in nni_listener_add_pipe ()
#4  0x0000562bf8950577 in listener_accept_cb ()
#5  0x0000562bf8958f21 in nni_taskq_thread ()
#6  0x0000562bf8959999 in nni_thr_wrap ()
#7  0x0000562bf895d206 in nni_plat_thr_main ()
#8  0x00007fe8a7a35609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#9  0x00007fe8a7754293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

### Disassembly

```
(gdb) disas
Dump of assembler code for function DJBHashn:
   0x0000562bf8962187 <+0>:	endbr64 
   0x0000562bf896218b <+4>:	push   %rbp
   0x0000562bf896218c <+5>:	mov    %rsp,%rbp
   0x0000562bf896218f <+8>:	mov    %rdi,-0x18(%rbp)
   0x0000562bf8962193 <+12>:	mov    %esi,%eax
   0x0000562bf8962195 <+14>:	mov    %ax,-0x1c(%rbp)
   0x0000562bf8962199 <+18>:	movl   $0x1505,-0x4(%rbp)
   0x0000562bf89621a0 <+25>:	movw   $0x0,-0x6(%rbp)
   0x0000562bf89621a6 <+31>:	jmp    0x562bf89621d8 <DJBHashn+81>
   0x0000562bf89621a8 <+33>:	mov    -0x4(%rbp),%eax
   0x0000562bf89621ab <+36>:	shl    $0x5,%eax
   0x0000562bf89621ae <+39>:	mov    %eax,%edx
   0x0000562bf89621b0 <+41>:	mov    -0x4(%rbp),%eax
   0x0000562bf89621b3 <+44>:	lea    (%rdx,%rax,1),%ecx
   0x0000562bf89621b6 <+47>:	mov    -0x18(%rbp),%rax
   0x0000562bf89621ba <+51>:	lea    0x1(%rax),%rdx
   0x0000562bf89621be <+55>:	mov    %rdx,-0x18(%rbp)
=> 0x0000562bf89621c2 <+59>:	movzbl (%rax),%eax
   0x0000562bf89621c5 <+62>:	movsbl %al,%eax
   0x0000562bf89621c8 <+65>:	add    %ecx,%eax
   0x0000562bf89621ca <+67>:	mov    %eax,-0x4(%rbp)
   0x0000562bf89621cd <+70>:	movzwl -0x6(%rbp),%eax
   0x0000562bf89621d1 <+74>:	add    $0x1,%eax
   0x0000562bf89621d4 <+77>:	mov    %ax,-0x6(%rbp)
   0x0000562bf89621d8 <+81>:	movzwl -0x6(%rbp),%eax
   0x0000562bf89621dc <+85>:	cmp    -0x1c(%rbp),%ax
   0x0000562bf89621e0 <+89>:	jb     0x562bf89621a8 <DJBHashn+33>
   0x0000562bf89621e2 <+91>:	andl   $0x7fffffff,-0x4(%rbp)
   0x0000562bf89621e9 <+98>:	mov    -0x4(%rbp),%eax
   0x0000562bf89621ec <+101>:	pop    %rbp
   0x0000562bf89621ed <+102>:	retq   
```

### Register

```
(gdb) i r
rax            0x0                 0
rbx            0x0                 0
rcx            0x2b5a5             177573
rdx            0x1                 1
rsi            0xffff              65535
rdi            0x0                 0
rbp            0x7fe8a4cd7c60      0x7fe8a4cd7c60
rsp            0x7fe8a4cd7c60      0x7fe8a4cd7c60
r8             0x7fe88c001ad0      140636757957328
r9             0x7c                124
r10            0x0                 0
r11            0x7fe88c000080      140636757950592
r12            0x7ffe95661bfe      140731404917758
r13            0x7ffe95661bff      140731404917759
r14            0x562bf89a5680      94746854446720
r15            0x7fe8a4cd7fc0      140637174071232
rip            0x562bf89621c2      0x562bf89621c2 <DJBHashn+59>
eflags         0x10206             [ PF IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
```

**Comment by JaylinYu** [comment]
Fixed in PR #224, the DJBHash method is no longer used for clientID hashing, a more elegant and efficient way is adopted.
Thank you for your advice!
