### ISSUE TITLE
Error happened in subscribing of mqttv5

### ISSUE THREAD

**Issue by wanghaEMQ** [nanomq/nanomq#315]
log from asan

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==26895==ERROR: AddressSanitizer: BUS on unknown address 0x000000000000 (pc 0x7f7949699a06 bp 0xbebebebebebebeae sp 0x7f79406f2a30 T12)
    #0 0x7f7949699a05  (/lib/x86_64-linux-gnu/libasan.so.5+0x28a05)
    #1 0x7f794977e798 in __interceptor_free (/lib/x86_64-linux-gnu/libasan.so.5+0x10d798)
    #2 0x558824f33e56 in nni_free /home/wangha/docu/git/nanomq/nng/src/platform/posix/posix_alloc.c:33
    #3 0x558824f038ca in nng_free /home/wangha/docu/git/nanomq/nng/src/nng.c:70
    #4 0x558824ea0bb1 in del_sub_ctx /home/wangha/docu/git/nanomq/nanomq/sub_handler.c:508
    #5 0x558824ef1998 in server_cb /home/wangha/docu/git/nanomq/nanomq/apps/broker.c:275
    #6 0x558824f2ec03 in nni_task_exec /home/wangha/docu/git/nanomq/nng/src/core/taskq.c:144
    #7 0x558824f12fa3 in nni_aio_finish_impl /home/wangha/docu/git/nanomq/nng/src/core/aio.c:456
    #8 0x558824f1328f in nni_aio_finish_sync /home/wangha/docu/git/nanomq/nng/src/core/aio.c:473
    #9 0x558824f5b281 in nano_pipe_close /home/wangha/docu/git/nanomq/nng/src/sp/protocol/mqtt/nmq_mqtt.c:646
    #10 0x558824f22ba2 in nni_pipe_close /home/wangha/docu/git/nanomq/nng/src/core/pipe.c:154
    #11 0x558824f5cd0e in nano_pipe_recv_cb /home/wangha/docu/git/nanomq/nng/src/sp/protocol/mqtt/nmq_mqtt.c:818
    #12 0x558824f2ec03 in nni_task_exec /home/wangha/docu/git/nanomq/nng/src/core/taskq.c:144
    #13 0x558824f12fa3 in nni_aio_finish_impl /home/wangha/docu/git/nanomq/nng/src/core/aio.c:456
    #14 0x558824f1328f in nni_aio_finish_sync /home/wangha/docu/git/nanomq/nng/src/core/aio.c:473
    #15 0x558824facd5c in tcptran_pipe_recv_cb /home/wangha/docu/git/nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:605
    #16 0x558824f2e40c in nni_taskq_thread /home/wangha/docu/git/nanomq/nng/src/core/taskq.c:50
    #17 0x558824f2f9e4 in nni_thr_wrap /home/wangha/docu/git/nanomq/nng/src/core/thread.c:94
    #18 0x558824f381de in nni_plat_thr_main /home/wangha/docu/git/nanomq/nng/src/platform/posix/posix_thread.c:266
    #19 0x7f7949657608 in start_thread /build/glibc-YbNSs7/glibc-2.31/nptl/pthread_create.c:477
    #20 0x7f7949573292 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x122292)
```

**Comment by wanghaEMQ** [comment]
Test passed
