### ISSUE TITLE
ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 

### ISSUE THREAD

**Issue by alvin1221** [nanomq/nanomq#319]
```bash
AddressSanitizer:DEADLYSIGNAL
=================================================================
==3232146==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f5d60215b9c bp 0x7f5d588f6600 sp 0x7f5d588f5d68 T9)
==3232146==The signal is caused by a READ memory access.
==3232146==Hint: address points to the zero page.
AddressSanitizer:DEADLYSIGNAL
    #0 0x7f5d60215b9b  (/lib/x86_64-linux-gnu/libc.so.6+0x181b9b)
    #1 0x7f5d6031fb0b  (/lib/x86_64-linux-gnu/libasan.so.5+0x74b0b)
    #2 0x55cbcb53a95b in decode_pub_message ../nanomq/pub_handler.c:656
    #3 0x55cbcb5386a5 in handle_pub ../nanomq/pub_handler.c:103
    #4 0x55cbcb551661 in server_cb ../nanomq/apps/broker.c:200
    #5 0x55cbcb58e4a9 in nni_task_exec ../nng/src/core/taskq.c:144
    #6 0x55cbcb572faa in nni_aio_finish_impl ../nng/src/core/aio.c:450
    #7 0x55cbcb57302c in nni_aio_finish_sync ../nng/src/core/aio.c:467
    #8 0x55cbcb5b6e1c in nano_pipe_recv_cb ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:883
    #9 0x55cbcb58e4a9 in nni_task_exec ../nng/src/core/taskq.c:144
    #10 0x55cbcb572faa in nni_aio_finish_impl ../nng/src/core/aio.c:450
    #11 0x55cbcb57302c in nni_aio_finish_sync ../nng/src/core/aio.c:467
    #12 0x55cbcb602756 in tlstran_pipe_recv_cb ../nng/src/sp/transport/mqtts/broker_tls.c:609
    #13 0x55cbcb58dcb2 in nni_taskq_thread ../nng/src/core/taskq.c:50
    #14 0x55cbcb58ef21 in nni_thr_wrap ../nng/src/core/thread.c:94
    #15 0x55cbcb59771b in nni_plat_thr_main ../nng/src/platform/posix/posix_thread.c:266
    #16 0x7f5d6029258f in start_thread nptl/pthread_create.c:463
    #17 0x7f5d601ad222 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x119222)


AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libc.so.6+0x181b9b) 
Thread T9 (nng:task) created by T0 here:
    #0 0x7f5d602e5805 in pthread_create (/lib/x86_64-linux-gnu/libasan.so.5+0x3a805)
    #1 0x55cbcb59784b in nni_plat_thr_init ../nng/src/platform/posix/posix_thread.c:279
    #2 0x55cbcb58f1ca in nni_thr_init ../nng/src/core/thread.c:121
    #3 0x55cbcb58dfd3 in nni_taskq_init ../nng/src/core/taskq.c:95
    #4 0x55cbcb58ebf1 in nni_taskq_sys_init ../nng/src/core/taskq.c:284
    #5 0x55cbcb579e6c in nni_init_helper ../nng/src/core/init.c:41
    #6 0x55cbcb597b9f in nni_plat_init ../nng/src/platform/posix/posix_thread.c:422
    #7 0x55cbcb579eeb in nni_init ../nng/src/core/init.c:63
    #8 0x55cbcb5bab88 in nni_proto_mqtt_open ../nng/src/sp/protocol.c:37
    #9 0x55cbcb5b755e in nng_nmq_tcp0_open ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:1035
    #10 0x55cbcb555b91 in broker ../nanomq/apps/broker.c:669
    #11 0x55cbcb558482 in broker_start ../nanomq/apps/broker.c:1100
    #12 0x55cbcb536767 in main ../nanomq/nanomq.c:187
    #13 0x7f5d600bccb1 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28cb1)

==3232146==ABORTING
```

**Comment by wanghaEMQ** [comment]
Please leave a way to reproduce it.
