### ISSUE TITLE
Segment fault

### ISSUE THREAD

**Issue by wanghaEMQ** [nanomq/nanomq#357]
Log from asan

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==2955491==ERROR: AddressSanitizer: SEGV on unknown address 0x603075ff0800 (pc 0x55e2b39f8dd7 bp 0x7f652b7f5aa0 sp 0x7f652b7f59f0 T10)
==2955491==The signal is caused by a WRITE memory access.
    #0 0x55e2b39f8dd7 in sub_ctx_handle ../nanomq/sub_handler.c:293
    #1 0x55e2b3a0eee7 in server_cb ../nanomq/apps/broker.c:357
    #2 0x55e2b3a4ae37 in nni_taskq_thread ../nng/src/core/taskq.c:50
    #3 0x55e2b3a4c0a4 in nni_thr_wrap ../nng/src/core/thread.c:94
    #4 0x55e2b3a5488a in nni_plat_thr_main ../nng/src/platform/posix/posix_thread.c:266
    #5 0x7f65338ca58f in start_thread nptl/pthread_create.c:463
    #6 0x7f65337c0222 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x119222)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../nanomq/sub_handler.c:293 in sub_ctx_handle
Thread T10 (nng:task) created by T0 here:
    #0 0x7f653393aa65 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:216
    #1 0x55e2b3a549ba in nni_plat_thr_init ../nng/src/platform/posix/posix_thread.c:279
    #2 0x55e2b3a4c34d in nni_thr_init ../nng/src/core/thread.c:121
    #3 0x55e2b3a4b156 in nni_taskq_init ../nng/src/core/taskq.c:95
    #4 0x55e2b3a4bd74 in nni_taskq_sys_init ../nng/src/core/taskq.c:284
    #5 0x55e2b3a3711c in nni_init_helper ../nng/src/core/init.c:41
    #6 0x55e2b3a54d0e in nni_plat_init ../nng/src/platform/posix/posix_thread.c:422
    #7 0x55e2b3a3719b in nni_init ../nng/src/core/init.c:63
    #8 0x55e2b3a78087 in nni_proto_mqtt_open ../nng/src/sp/protocol.c:37
    #9 0x55e2b3a74a5d in nng_nmq_tcp0_open ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:1049
    #10 0x55e2b3a126a4 in broker ../nanomq/apps/broker.c:742
    #11 0x55e2b3a14f8e in broker_start ../nanomq/apps/broker.c:1173
    #12 0x55e2b39f21ed in main ../nanomq/nanomq.c:187
    #13 0x7f65336cfcb1 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28cb1)
```

**Comment by wanghaEMQ** [comment]
How to reproduce ?

```
Using nftp file recver

./build/mqtt_nftp_recver

mosquitto_pub -t test/room1/emqx/client/user1 -h iot-platform.cloud -d -m "{\"cmd\":\"send\",\"sendpath\":\"C:\\\\\",\"recvpath\":\"\",\"filename\":\"NBA.png\"}" -u KZJJJJJJ-cmduser -P bc829377a311a1abe192a9b0TTTd88d2
```

**Comment by wanghaEMQ** [comment]
It seems fixed when testing with the latest master branch
