### ISSUE TITLE
deadlock

### ISSUE THREAD

**Issue by wanghaEMQ** [nanomq/nanomq#395]
log from nng

```
panic: pthread_mutex_lock: Resource deadlock avoided
This message is indicative of a BUG.
Report this at https://github.com/nanomq/nanomq
./build/nanomq/nanomq(nni_show_backtrace+0xb8) [0x55ba2cc1f870]
./build/nanomq/nanomq(nni_panic+0x1ca) [0x55ba2cc1fb7e]
./build/nanomq/nanomq(+0xd6bca) [0x55ba2cc34bca]
./build/nanomq/nanomq(nni_plat_mtx_lock+0x1c) [0x55ba2cc34d8b]
./build/nanomq/nanomq(nni_mtx_lock+0x1c) [0x55ba2cc2c92a]
./build/nanomq/nanomq(+0xea6af) [0x55ba2cc486af]
./build/nanomq/nanomq(nni_ctx_send+0xca) [0x55ba2cc27209]
./build/nanomq/nanomq(nng_ctx_send+0x1be) [0x55ba2cc04497]
./build/nanomq/nanomq(server_cb+0x2e1d) [0x55ba2cbf24bc]
./build/nanomq/nanomq(+0xcd92a) [0x55ba2cc2b92a]
./build/nanomq/nanomq(+0xceb99) [0x55ba2cc2cb99]
./build/nanomq/nanomq(+0xd7393) [0x55ba2cc35393]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x9609) [0x7fcf9ecff609]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7fcf9ec1b293]
[1]    55281 abort (core dumped)  ./build/nanomq/nanomq broker start -D 3
```

## How to reproduce
./build/nanomq/nanomq broker start -D 3

mosquitto_sub -t msg/a -i clia -d -c -q 2
Stop

mosquitto_pub -t msg/a -q 2 -m "aaa"
mosquitto_pub -t msg/a -q 2 -m "aaa"

> If the deadlock is not being triggered, try more ...

**Comment by wanghaEMQ** [comment]
```
Thread 16 "nng:task" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffecdf1700 (LWP 56931)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff737d859 in __GI_abort () at abort.c:79
#2  0x0000555555628ec2 in nni_plat_abort () at ../nng/src/platform/posix/posix_debug.c:23
#3  0x0000555555615b83 in nni_panic (fmt=0x5555556d5120 "pthread_mutex_lock: %s")
    at ../nng/src/core/panic.c:66
#4  0x000055555562abca in nni_pthread_mutex_lock (m=0x61d00000fd68)
    at ../nng/src/platform/posix/posix_thread.c:85
#5  0x000055555562ad8b in nni_plat_mtx_lock (mtx=0x61d00000fd68)
    at ../nng/src/platform/posix/posix_thread.c:146
#6  0x000055555562292a in nni_mtx_lock (mtx=0x61d00000fd68) at ../nng/src/core/thread.c:27
#7  0x000055555563e6af in nano_ctx_send (arg=0x6100000011b0, aio=0x615000003000)
    at ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:406
#8  0x000055555561d209 in nni_ctx_send (ctx=0x610000001140, aio=0x615000003000)
    at ../nng/src/core/socket.c:1344
#9  0x00005555555fa497 in nng_ctx_send (cid=..., aio=0x615000003000) at ../nng/src/nng.c:369
#10 0x00005555555e84bc in server_cb (arg=0x60c000000dc0) at ../nanomq/apps/broker.c:429
#11 0x000055555562192a in nni_taskq_thread (self=0x61b000000620) at ../nng/src/core/taskq.c:50
#12 0x0000555555622b99 in nni_thr_wrap (arg=0x61b000000628) at ../nng/src/core/thread.c:94
#13 0x000055555562b393 in nni_plat_thr_main (arg=0x61b000000628)
    at ../nng/src/platform/posix/posix_thread.c:266
#14 0x00007ffff755e609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#15 0x00007ffff747a293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
