### ISSUE TITLE
Bridge caused heap-buffer-overflow.

### ISSUE THREAD

**Issue by lee-emqx** [nanomq/nanomq#436]
Compile nanomq with asan on mac, run cmd `./nanomq/nanomq broker start --bridge ../etc/nanomq_bridge.conf` got error below.

```
➜  build git:(master) ✗ ./nanomq/nanomq broker start --bridge ../etc/nanomq_bridge.conf

=================================================================
==37477==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x603000007586 at pc 0x00010443d634 bp 0x7ffeebab6e70 sp 0x7ffeebab6630
READ of size 23 at 0x603000007586 thread T0
    #0 0x10443d633 in wrap_strlen+0x183 (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x1a633)
    #1 0x7fff6b552158 in vsscanf_l+0x7f (libsystem_c.dylib:x86_64+0x4f158)
    #2 0x104446fe9 in wrap_sscanf+0xd9 (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x23fe9)
    #3 0x104194536 in get_conf_value conf.c:151
    #4 0x104196dff in conf_bridge_parse conf.c:570
    #5 0x1041dcac2 in broker_start broker.c:1123
    #6 0x10419f811 in main nanomq.c:187
    #7 0x7fff6b4b3cc8 in start+0x0 (libdyld.dylib:x86_64+0x1acc8)

0x603000007586 is located 0 bytes to the right of 22-byte region [0x603000007570,0x603000007586)
allocated by thread T0 here:
    #0 0x10446c552 in wrap_calloc+0xa2 (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x49552)
    #1 0x104198f09 in strtrim conf.c:20
    #2 0x104194506 in get_conf_value conf.c:149
    #3 0x104196dff in conf_bridge_parse conf.c:570
    #4 0x1041dcac2 in broker_start broker.c:1123
    #5 0x10419f811 in main nanomq.c:187
    #6 0x7fff6b4b3cc8 in start+0x0 (libdyld.dylib:x86_64+0x1acc8)

SUMMARY: AddressSanitizer: heap-buffer-overflow (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x1a633) in wrap_strlen+0x183
Shadow bytes around the buggy address:
  0x1c0600000e60: fd fd fd fa fa fa fd fd fd fd fa fa fd fd fd fa
  0x1c0600000e70: fa fa fd fd fd fd fa fa fd fd fd fa fa fa fd fd
  0x1c0600000e80: fd fd fa fa fd fd fd fa fa fa fd fd fd fd fa fa
  0x1c0600000e90: fd fd fd fa fa fa fd fd fd fd fa fa fd fd fd fa
  0x1c0600000ea0: fa fa fd fd fd fd fa fa 00 00 00 00 fa fa 00 00
=>0x1c0600000eb0:[06]fa fa fa 00 00 00 00 fa fa fa fa fa fa fa fa
  0x1c0600000ec0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0600000ed0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0600000ee0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0600000ef0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0600000f00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==37477==ABORTING
[1]    37477 abort      ./nanomq/nanomq broker start --bridge ../etc/nanomq_bridge.conf
```

**Comment by JaylinYu** [comment]
fixed by #437
