### ISSUE TITLE
detree_ctx is NULL when client disconnected

### ISSUE THREAD

**Issue by JaylinYu** [nanomq/nanomq#445]
Sun Mar 20 13:43:07 2022 tcptran_pipe_recv_cb: remain_len 0 cparam 0x61200001ffc0 clientid mqttx_33927a6f username 1234 proto 4

Sun Mar 20 13:43:07 2022 tcptran_pipe_recv_cb: The type of msg is e0
Sun Mar 20 13:43:07 2022 nni_aio_finish_sync: Hunky dory(0)
Sun Mar 20 13:43:07 2022 nano_pipe_recv_cb: ######### nano_pipe_recv_cb ############
Sun Mar 20 13:43:07 2022 nano_pipe_close:  ############## nano_pipe_close ############## 
Sun Mar 20 13:43:07 2022 nni_aio_finish_error: Object closed(7)
Sun Mar 20 13:43:07 2022 nni_aio_finish_sync: Hunky dory(0)
Sun Mar 20 13:43:07 2022 server_cb: RECV  ^^^^ ctx9 ^^^^

Sun Mar 20 13:43:07 2022 decode_pub_message: cmd: 3, retain: 0, qos: 0, dup: 0, remaining length: 108
Sun Mar 20 13:43:07 2022 decode_pub_message: topic: [$SYS/brokers/disconnected], qos: 0
Sun Mar 20 13:43:07 2022 decode_pub_message: used pos: [27]
Sun Mar 20 13:43:07 2022 decode_pub_message: payload: [{"username":"1234","ts":275660846,"reason_code":"0","client_id":"mqttx_33927a6f"}], len = 81
Sun Mar 20 13:43:07 2022 handle_pub: pipe_info size: [0]
[INFO] Sun Mar 20 13:43:07 2022 (140144533292608:search_and_delete:1339) topic is: testtopic, node->topic is: she
[INFO] Sun Mar 20 13:43:07 2022 (140144533292608:search_and_delete:1339) topic is: #, node->topic is: #
[INFO] Sun Mar 20 13:43:07 2022 (140144533292608:search_and_delete:1374) Search and delete client
[INFO] Sun Mar 20 13:43:07 2022 (140144533292608:search_and_delete:1375) node->topic: testtopic
____________PRINT_DB_CLIENT___________
1145608179	
____________PRINT_DB_CLIENT___________
____________PRINT_DB_CLIENT___________

____________PRINT_DB_CLIENT___________
[INFO] Sun Mar 20 13:43:07 2022 (140144533292608:dbtree_client_free:298) Delete client pipe_id: [1145608179]
[INFO] Sun Mar 20 13:43:07 2022 (140144533292608:delete_dbtree_node:1178) Delete node: [#]
[INFO] Sun Mar 20 13:43:07 2022 (140144533292608:delete_dbtree_node:1178) Delete node: [testtopic]
Sun Mar 20 13:43:07 2022 del_sub_ctx: FREE in topic_node [testtopic/#] in tree
Sun Mar 20 13:43:07 2022 del_sub_ctx: info: sub pkt node handling [0x60200001d1d0]

[INFO] Sun Mar 20 13:43:07 2022 (140144533292608:search_and_delete:1339) topic is: she, node->topic is: she
[INFO] Sun Mar 20 13:43:07 2022 (140144533292608:search_and_delete:1339) topic is: +, node->topic is: +
[INFO] Sun Mar 20 13:43:07 2022 (140144533292608:search_and_delete:1339) topic is: relay, node->topic is: relay
[INFO] Sun Mar 20 13:43:07 2022 (140144533292608:search_and_delete:1339) topic is: 0, node->topic is: 0
[INFO] Sun Mar 20 13:43:07 2022 (140144533292608:search_and_delete:1339) topic is: energy, node->topic is: 0
[INFO] Sun Mar 20 13:43:07 2022 (140144533292608:search_and_delete:1361) searching unequal
AddressSanitizer:DEADLYSIGNAL
=================================================================
==208364==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x55d27407f7cd bp 0x7f75f11fb5f0 sp 0x7f75f11fb2e0 T4)
==208364==The signal is caused by a READ memory access.
==208364==Hint: address points to the zero page.
    #0 0x55d27407f7cd in server_cb ../nanomq/apps/broker.c:278
    #1 0x55d2740c6a9d in nni_task_exec ../nng/src/core/taskq.c:144
    #2 0x55d2740aac82 in nni_aio_finish_impl ../nng/src/core/aio.c:450
    #3 0x55d2740aaf6e in nni_aio_finish_sync ../nng/src/core/aio.c:467
    #4 0x55d2740ea238 in nano_pipe_close ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:776
    #5 0x55d2740bab2c in nni_pipe_close ../nng/src/core/pipe.c:137
    #6 0x55d2740ebce9 in nano_pipe_recv_cb ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:957
    #7 0x55d2740c6a9d in nni_task_exec ../nng/src/core/taskq.c:144
    #8 0x55d2740aac82 in nni_aio_finish_impl ../nng/src/core/aio.c:450
    #9 0x55d2740aaf6e in nni_aio_finish_sync ../nng/src/core/aio.c:467
    #10 0x55d27414ef39 in tcptran_pipe_recv_cb ../nng/src/sp/transport/mqtt/broker_tcp.c:720
    #11 0x55d2740c62a8 in nni_taskq_thread ../nng/src/core/taskq.c:50
    #12 0x55d2740c787b in nni_thr_wrap ../nng/src/core/thread.c:94
    #13 0x55d2740d0061 in nni_plat_thr_main ../nng/src/platform/posix/posix_thread.c:266
    #14 0x7f75f6171946 in start_thread nptl/pthread_create.c:435
    #15 0x7f75f6201a43 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x124a43)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../nanomq/apps/broker.c:278 in server_cb
Thread T4 created by T0 here:
    #0 0x7f75f6381685 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:216
    #1 0x55d2740d0191 in nni_plat_thr_init ../nng/src/platform/posix/posix_thread.c:279
    #2 0x55d2740c7b24 in nni_thr_init ../nng/src/core/thread.c:121
    #3 0x55d2740c65c7 in nni_taskq_init ../nng/src/core/taskq.c:95
    #4 0x55d2740c754b in nni_taskq_sys_init ../nng/src/core/taskq.c:284
    #5 0x55d2740b2734 in nni_init_helper ../nng/src/core/init.c:35
    #6 0x55d2740d04e5 in nni_plat_init ../nng/src/platform/posix/posix_thread.c:422
    #7 0x55d2740b27b2 in nni_init ../nng/src/core/init.c:58
    #8 0x55d2741038b4 in nng_thread_create ../nng/src/supplemental/util/platform.c:42
    #9 0x55d27406c6a0 in start_rest_server ../nanomq/web_server.c:437
    #10 0x55d2740880a4 in broker_start ../nanomq/apps/broker.c:1147
    #11 0x55d27404e84d in main ../nanomq/nanomq.c:187
    #12 0x7f75f6106fcf in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

==208364==ABORTING

**Comment by JaylinYu** [comment]
client must subs
she/+/relay/0/energy
she/+/relay/0
#
at same time
